#+TITLE: The Translator Module
#+AUTHOR: VLEAD
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  The Translators module is a micro-service part of the VLabs platform
  [[https://github.com/vlead/vlabs-platform/blob/refactoring/src/design/index.org][=design=]]. The module works as skeleton generator for an experiment.

* Design of the application
  The Translators app accepts a lab specification for an experiment through
  its [[./runtime/rest/index.org][=REST=]] interface. The [[./runtime/rest/index.org][=REST=]] module interacts with the [[./runtime/system/index.org][=system=]] module
  through the system interface and generates a version controlled experiment on
  a remote Github server.

  The Translators app can also use the [[../openedx/index.org][=openedx=]] module and generate the lab
  specification structure for openedx that can be deployed on the previous version of the
  vlabs platform. The [[./system/index.org][=system=]] module executes the automated script of the
  [[../openedx/index.org][=openedx=]] module and generates the lab structure specific to openedx.

* Components of the application directory

  - [[./deployment/index.org][=deployment=]]

  - [[./runtime/index.org][=runtime=]]

  - [[./openedx/index.org][=openedx=]]

* Tangle
#+BEGIN_SRC python :eval no :tangle __init__.py
print("Translators package")

#+END_SRC
